### ISSUE TITLE
Add Collabora to the list?

### ISSUE THREAD

**Issue by szaimen** [offa/android-foss#108]
Hi, afaik there is no open source office app out there for Android apart from collabora.
Would it make sense to integrate them into the list?
They just made a f-droid repo avilable:
https://gitlab.com/fdroid/rfp/-/issues/1399#note_427074031

**Comment by offa** [comment]
Generally speaking yes, but but I'm a bit confused what parts of collabora are actually FOSS (not which not).

F-Droid repositories are limited to the official F-Droid ones.

**Comment by szaimen** [comment]
Afaik this app is FOSS.
Since they made an own F-Droid repo I guess we can close this issue since it most likely will not be available on the official one...

**Comment by offa** [comment]
Ok, thanks anyway!

**Comment by szaimen** [comment]
BTW: here is the source code:
https://git.libreoffice.org/online/+/master/android
here is their official website:
https://www.collaboraoffice.com/solutions/collabora-office-android-ios/

Maybe it could look like this:
### • Office
- [**Collabora**](https://www.collaboraoffice.com/solutions/collabora-office-android-ios/) <sup>**[[source-code](https://git.libreoffice.org/online/+/master/android)]**</sup>

**Comment by offa** [comment]
I see, typically one link — either source code or website — is enough. As the repo is linked in the website, I guess the website is suited best.

Could you provide a PR?

**Comment by szaimen** [comment]
> Could you provide a PR?

Done with #113
