### ISSUE TITLE
A lot of Apps

### ISSUE THREAD

**Issue by RickyM7** [offa/android-foss#110]
### Please add these apps to the list.

**1. Name: SmartCookieWeb**

Description: A Secure, Free and Open Source WebView-based web browser for Android. A fork of Lightning Browser.

Category: Browser

Links:
Source: https://github.com/CookieJarApps/SmartCookieWeb
F-Droid: https://f-droid.org/en/packages/com.cookiegames.smartcookie
Play Store: https://play.google.com/store/apps/details?id=com.cookiegames.smartcookie
Website: https://smartcookieweb.com

**2. Name: Twire**

Description: An Open Source, AD-Free Twitch browser and stream player for Android. Supports VODs with chat replay, custom emotes (BTTV and FFZ) and Picture in Picture mode. A fork of Pocket Plays for Twitch.

Category: Media Frontends

Links:
Source: https://github.com/twireapp/Twire
F-Droid: https://f-droid.org/packages/com.perflyst.twire

**3. Name: Music Player GO**

Description: A simple yet fully-featured local music player aiming at simplicity and performance.

Category: Music & Audio Player

Links:
Source: https://github.com/enricocid/Music-Player-GO
F-Droid: https://f-droid.org/packages/com.iven.musicplayergo
Play Store: https://play.google.com/store/apps/details?id=com.iven.musicplayergo

**4. Name: OctoDroid**

Description: Github client for Android.

Category: Community Clients?

Links:
Source: https://github.com/slapperwan/gh4a
F-Droid: https://f-droid.org/packages/com.gh4a
Play Store: https://play.google.com/store/apps/details?id=com.gh4a

**5. Name: Twidere**

Description: An Open Source, fully featured Twitter/Mastodon/StatusNet/Fanfou app.

Category: Community Clients

Links:
Source: https://github.com/TwidereProject/Twidere-Android
F-Droid: https://f-droid.org/repository/browse/?fdid=org.mariotaku.twidere
Play Store: https://play.google.com/store/apps/details?id=org.mariotaku.twidere
Website: https://twidere.com

**6. Name: Tachiyomi**

Description: A Free and Open Source manga reader for Android.

Category: Miscellaneous? Entertainment?

Links:
Source: https://github.com/inorichi/tachiyomi
F-Droid: https://f-droid.org/en/packages/eu.kanade.tachiyomi
Website: https://tachiyomi.org

**7. Name: Librera Reader PRO**

Description: An e-book reader for Android devices; it supports the following formats: PDF, EPUB, EPUB3, MOBI, DjVu, FB2, TXT, RTF, AZW, AZW3, HTML, CBZ, CBR, DOC, DOCX, and OPDS Catalogs.

Category: Document & PDF Viewer

Links:
Source: https://github.com/foobnix/LibreraReader
F-Droid: https://f-droid.org/en/packages/com.foobnix.pro.pdf.reader
Play Store: https://play.google.com/store/apps/details?id=com.foobnix.pro.pdf.reader
Website: http://librera.mobi

**8. Name: Download Navi**

Description: A Free and Open Source software download manager.

Category: Utilities?

Links:
Source: https://github.com/TachibanaGeneralLaboratories/download-navi
F-Droid: https://f-droid.org/en/packages/com.tachibana.downloader
Play Store: https://play.google.com/store/apps/details?id=com.tachibana.downloader

**9. Name: CPU Info**

Description: Provides information about device hardware and software.

Category: Utilities?

Links:
Source: https://github.com/kamgurgul/cpu-info
F-Droid: https://f-droid.org/packages/com.kgurgul.cpuinfo
Play Store: https://play.google.com/store/apps/details?id=com.kgurgul.cpuinfo

**10. Name: Foxy Droid**

Description: Yet another F-Droid client.

Category: App Store
 
Links:
Source: https://github.com/kitsunyan/foxy-droid
F-Droid: https://f-droid.org/en/packages/nya.kitsunyan.foxydroid

**11. Name: Infinity for Reddit**

Description: A beautiful, feature-rich app that offers a smooth Reddit browsing experience. It is completely free and ad-less; you can browse Reddit without interruptions or distractions. Built by a passionate university student, Infinity is open source.

Category: Community Clients

Links:
Source: https://github.com/Docile-Alligator/Infinity-For-Reddit
F-Droid: https://apt.izzysoft.de/fdroid/index/apk/ml.docilealligator.infinityforreddit
Play Store: https://play.google.com/store/apps/details?id=ml.docilealligator.infinityforreddit

**Comment by offa** [comment]
Nice, thank you! I'll have look at them 👍.

**Comment by RickyM7** [comment]
Thank you!

**Comment by offa** [comment]
All added, except the 3rd party F-Droid repo of Infinity. However, there's already an ongoing [request for packaging](https://gitlab.com/fdroid/rfp/-/issues/1394) for the official repo.

**Comment by RickyM7** [comment]
Nice, thank you!

**Comment by offa** [comment]
Better late than never: Infinity F-Droid link added, it's available through the official repo.

/cc @RickyM7
