### ISSUE TITLE
App recommendation (Keepass2Android)

### ISSUE THREAD

**Issue by tegutistgut** [offa/android-foss#123]
Hello,
Keepass2Android is a open source password manager based on KeePass.
It has a integrated keyboard to counter clipboard spoofing.

**Comment by offa** [comment]
Thanks for the suggestion.

After reading through [here](https://github.com/PhilippC/keepass2android/issues/38) I guess KeePassDX is a better choice.

**Comment by offa** [comment]
According to the link discussion, it includes proprietary parts. The F-Droid and proper FOSS version seem to be stalled.

Feel free to reopen, if there's any update.
