### ISSUE TITLE
App proposal: Photok

### ISSUE THREAD

**Issue by comparesheriff** [offa/android-foss#131]
### Short Description: 
Photok encrypts your photos locally on your device and keeps them safe from others.

### Source:
[https://github.com/leonlatsch/Photok](https://github.com/leonlatsch/Photok)

### License:
Apache

### F-Droid:
https://f-droid.org/packages/dev.leonlatsch.photok/

### Category:
Utilities, Privacy, Misc ?

**Comment by offa** [comment]
Thanks for your suggestion. I've added it under *Utilities*, other suggestion are still welcome though! :+1:
