### ISSUE TITLE
Maps.ME

### ISSUE THREAD

**Issue by tGstep** [offa/android-foss#138]
Why is here Maps.ME? It's not a closed source app?

**Comment by offa** [comment]
According to it's [repo](https://github.com/mapsme/omim) it's Apache 2.0. But after talking a look into the source and a related [RFP on F-Droid](https://gitlab.com/fdroid/rfp/-/issues/87) it turned out to contain proprietary parts.

Thanks for reporting, I'm going to remove it.

**Comment by offa** [comment]
Related upstream discussion: https://github.com/mapsme/omim/issues/85
