### ISSUE TITLE
Bromite on F-Droid

### ISSUE THREAD

**Issue by Raanelom** [offa/android-foss#156]
The README.md says Bromite isn't available on F-Droid. However, with some additional configuration it is available via F-Droid: https://www.bromite.org/fdroid

**Comment by offa** [comment]
> The README.md says Bromite isn't available on F-Droid. 

… on the _official_ F-Droid repo :-)

There's an ongoing [packaging request on F-Droid](https://gitlab.com/fdroid/rfp/-/issues/378), but Chromium based projects seem really tricky. Related upstream discussion: https://github.com/bromite/bromite/issues/4

**Comment by Raanelom** [comment]
Ah thanks for the clarification (and the nice overview, in general)

**Comment by offa** [comment]
@Raanelom Can we close here?

**Comment by Raanelom** [comment]
Yes!

-------- Original Message --------
