### ISSUE TITLE
Categories and apps suggestions

### ISSUE THREAD

**Issue by Relwi** [offa/android-foss#176]
**Categories** (or maybe put the apps in other categories?)
- Anime & Manga

**Applications:**
- **Fritter**
  - **Description:** A privacy-friendly Twitter frontend for mobile devices.
  - **Repository:** https://github.com/jonjomckay/fritter
  - **F-Droid:** https://f-droid.org/app/com.jonjomckay.fritter
- **Ghost Commander**
  - **Description:** Dual panel file manager, like Norton Commander, Midnight Commander or Total
Commander.
  - **Repository:** https://sourceforge.net/p/ghostcommander/svn/HEAD/tree
  - **F-Droid:** https://f-droid.org/app/com.ghostsq.commander
- **Jellyfin**
  - **Description:** Android app that connects to Jellyfin instances.
  - **Repository:** https://github.com/jellyfin/jellyfin-android
  - **F-Droid:** https://f-droid.org/app/org.jellyfin.mobile
- **Kotatsu**
  - **Description:** Free and open source manga reader for Android.
  - **Repository:** https://github.com/nv95/Kotatsu
  - **F-Droid:** https://f-droid.org/app/org.koitharu.kotatsu
- **Nekome**
  - **Description:** Android application that helps with tracking your anime and manga watch lists.
  - **Repository:** https://github.com/Chesire/Nekome
  - **F-Droid:** https://f-droid.org/app/com.chesire.nekome
- **Stealth**
  - **Description:** Account-free, privacy-oriented, and feature-rich Reddit client.
  - **Repository:** https://gitlab.com/cosmosapps/stealth
  - **F-Droid:** https://f-droid.org/app/com.cosmos.unreddit

**Comment by offa** [comment]
Thanks for your suggestions.

AL-chan, AniLib and Showly contain proprietary components like firebase unfortunately. 

Nekome looks fine – if there's no suited category, we can add it of course.

**Comment by Relwi** [comment]
Oh okay, and how you check if the apps has proprietary components? Viewing in the build.gradle file? For the next time.

**Comment by offa** [comment]
Sometimes it's enough to read the comments of F-Droid requests or related packaging topics. But yes, talking a look into the build files or imports is a good starting point.

In doubt, feel free to open an issue / PR here anyway and I'll try to help out.

**Comment by Relwi** [comment]
Some other apps added, let me know please if the apps are correct to add, I can create the PR too if you want.

**Comment by offa** [comment]
All fine and PRs are always welcome :+1:
