### ISSUE TITLE
FileSharing

### ISSUE THREAD

**Issue by Paiusco** [offa/android-foss#188]
- Are you aware that TrebleShot is saying on its repo that will no longer receive features or bug updates [here]? It's good for for to know that the projects here listed are not deprecated (https://github.com/trebleshot/android#important-project-deprecation)

- Snapdrop may be a good option for substitution or add. [Repo](https://github.com/fm-sys/snapdrop-android) 

Congratulations on the repo, very helpful! :) 
Created PR #189 to _fix_ it

**Comment by offa** [comment]
Thanks for your PR, I have linked it to the issue.
