### ISSUE TITLE
Games category

### ISSUE THREAD

**Issue by shuvashish76** [offa/android-foss#199]
Hello I'd like to add few games to a new category called "Games" just like we have App Store & Apps category.

![Screenshot_2022-02-03-12-18-13](https://user-images.githubusercontent.com/48226312/152542567-09644579-a860-4e7a-8969-44a1e1f08b67.jpeg)
_screenshot source: [Aurora Store](https://f-droid.org/app/com.aurora.store)_

I think I'll pick sub-category keeping this as reference or [wikipedia](https://en.wikipedia.org/wiki/List_of_types_of_games) as reference.

Need @offa your permisson regarding this.

ThankYou🙏🏿

**Comment by offa** [comment]
Sounds good, please make it a subsection of "Apps" though (Apps –> Games –> …).

**Comment by offa** [comment]
PR #200 merged.
