### ISSUE TITLE
nicownng - japanese fdroid keyboard, korean - fdroid florisboard recent fork.

### ISSUE THREAD

**Issue by Jirafey** [offa/android-foss#215]
add nicownng to the keyboards for the Japanese writing just like Trime offers (only with Termux from fdroid), Florisboard is the only foss app that supposrts korean keyboard full, there is a forked version of it that fully supports korean ime. https://github.com/florisboard/florisboard/actions/runs/2099043140

**Comment by offa** [comment]
Thanks for the suggestion, but the development looks inactive and the project itself has been archived (probably due to Bitbuckets Mercurial sunset?). Last release was quite some years ago.

On F-Droid: https://f-droid.org/app/net.gorry.android.input.nicownng

**Comment by Jirafey** [comment]
> Thanks for the suggestion, but the development looks inactive and the project itself has been archived (probably due to Bitbuckets Mercurial sunset?). Last release was quite some years ago.
> 
> On F-Droid: https://f-droid.org/app/net.gorry.android.input.nicownng

I mean keyboard works fine without the development, setup is a bit hard since its all in japanese but it can be figured out. There is just no other option than this which is both foss and privacy friendly. It is really really hard to find something like an asian language keyboard that does not track you. Putting it there would make a huge difference for someone :)
