### ISSUE TITLE
List for tools

### ISSUE THREAD

**Issue by offa** [offa/android-foss#249]
Integrate FOSS tools, typically not running on the device itself (see #248 discussion).

#### Possible solutions:

1. Introduce a Tools section
2. Create an additional file and link from main file
3. …

Please let me know what you think.

**Comment by offa** [comment]
> @offa Please keep this issue open 30-45 days for others opinion on this.

Yes, and I've pinned it.

**Comment by invinciblevenom** [comment]
I am also in favour of this section!

**Comment by offa** [comment]
Thanks for you feedback, I have added the section :-)

**Comment by offa** [comment]
- [x] Universal Android Debloater GUI - https://github.com/0x192/universal-android-debloater — #248 
- [ ] Apktool - https://github.com/iBotPeaches/Apktool
- [x] ~~APK Studio - https://github.com/vaibhavpandeyvpz/apkstudio~~ — no longer maintained
- [ ] APKLab - https://github.com/APKLab/APKLab
- [ ] APK Editor Studio - https://github.com/kefir500/apk-editor-studio
