### ISSUE TITLE
[Messaging] - qaul – قول

### ISSUE THREAD

**Issue by MadTooth** [offa/android-foss#259]
https://github.com/qaul/qaul.net

**Comment by offa** [comment]
Thanks for your suggestion. The project includes proprietary Google Play services, do you know whether there's a FOSS build flavour available?

**Comment by MadTooth** [comment]
Write more precisely ! In what file did you find "proprietary Google Play services" ?

**Comment by MadTooth** [comment]
Understood :]

**Comment by offa** [comment]
It's always a good idea to ask the maintainer for a FOSS flavour and/or F-Droid inclusion btw. :-)

**Comment by MadTooth** [comment]
Done - https://github.com/qaul/qaul.net/issues/512
