### ISSUE TITLE
Add Social Media Section

### ISSUE THREAD

**Issue by RustoMCSpit** [offa/android-foss#290]
https://github.com/dessalines/jerboa

https://github.com/liftoff-app/liftoff/releases

https://github.com/tuskyapp/Tusky

https://github.com/mastodon/mastodon-android

**Comment by shuvashish76** [comment]
liftoff - Yes I noticed that app, waiting for F-Droid release. https://github.com/liftoff-app/liftoff/issues/47
Others - already available in the list

**Comment by RustoMCSpit** [comment]
> liftoff - Yes I noticed that app, waiting for F-Droid release. [liftoff-app/liftoff#47](https://github.com/liftoff-app/liftoff/issues/47) Others - already available in the list

under what section?

**Comment by shuvashish76** [comment]
Use "Ctrl+F" or "Find in page" to search keywords on your browser ;)

**Comment by offa** [comment]
> liftoff - Yes I noticed that app, waiting for F-Droid release. liftoff-app/liftoff#47

The F-Droid rfp seems only blocked by technical issues, the project itself seems ok. Unless objections, we can include it now and add the F-Droid link later.

**Comment by shuvashish76** [comment]
Another Lemmy client : https://github.com/thunder-app/thunder/issues/347

**Comment by RustoMCSpit** [comment]
is revolt foss

**Comment by shuvashish76** [comment]
https://codeberg.org/Bazsalanszky/Infinity-For-Lemmy
Lemmy clients raining...

**Comment by offa** [comment]
> Another Lemmy client : [thunder-app/thunder#347](https://github.com/thunder-app/thunder/issues/347)

Seems to include Google APIs according to search, but I'm not very similar with flutter projects.

**Comment by shuvashish76** [comment]
> thunder : seems to include Google APIs according to searc

https://apt.izzysoft.de/fdroid/index/apk/com.hjiangsu.thunder
Seems nothing detected in izzy libraries scanner.

**Comment by offa** [comment]
Thanks, I did a simple text search. But it seems ok then, I'm going to update the comment above.

**Comment by offa** [comment]
Is someone interested in submitting those as PR? I don't have time today, but I can do it the next days.

**Comment by shuvashish76** [comment]
I've few more apps in my list for August update, assign this to me.

**Comment by offa** [comment]
Perfect, thank you! :tada:

**Comment by shuvashish76** [comment]
> Slide

As per their README it's a WIP project, let's not include it for now.
https://github.com/bqv/slide/issues/55
