### ISSUE TITLE
add a widget section for foss widgets

### ISSUE THREAD

**Issue by RustoMCSpit** [offa/android-foss#293]

**Comment by RustoMCSpit** [comment]
https://github.com/Xlythe/MinecraftClock for example

**Comment by RustoMCSpit** [comment]
https://github.com/elboza/footguy

**Comment by offa** [comment]
Thanks for the suggestion.

Both projects look inactive though.

**Comment by shuvashish76** [comment]
To me both projects looks dead even the bones vaporized ☠️

**Comment by RustoMCSpit** [comment]
find other widgets then lol, the category still shiuld be adxed

**Comment by shuvashish76** [comment]
We don't create categories 1st then search apps to fit into it.

**Comment by offa** [comment]
I'm closing here. Section is added once there are enough entries.

**Comment by RustoMCSpit** [comment]
> I'm closing here. Section is added once there are enough entries.

wait so did you add a section?

**Comment by RustoMCSpit** [comment]
confused, i cant see it

**Comment by offa** [comment]
> wait so did you add a section?

No, I'm adding it once there are enough entries. At the moment there are none.
