### ISSUE TITLE
are there any tag editors?

### ISSUE THREAD

**Issue by RustoMCSpit** [offa/android-foss#296]

**Comment by offa** [comment]
Sorry, can you explain your question a little more?

**Comment by RustoMCSpit** [comment]
> Sorry, can you explain your question a little more?

a tag editor is a type of app

**Comment by shuvashish76** [comment]
What is your use case ?

**Comment by offa** [comment]
> > Sorry, can you explain your question a little more?
> 
> a tag editor is a type of app

But what's the point of the question?

**Comment by RustoMCSpit** [comment]
> > > Sorry, can you explain your question a little more?
> > 
> > 
> > a tag editor is a type of app
> 
> But what's the point of the question?

are there any tag editors that fit the requirements to list

**Comment by shuvashish76** [comment]
Not sure if you're looking https://github.com/tagspaces/tagspaces this type of apps.
I don't think we need a special category for now.

**Comment by offa** [comment]
Indeed; once there are enough entries to create a section we can create it – but let's not force it.

**Comment by offa** [comment]
I'm closing here as it's still not clear what to do here.
