### ISSUE TITLE
Obtainium

### ISSUE THREAD

**Issue by Hate9** [offa/android-foss#299]
https://github.com/ImranR98/Obtainium
It's an app store that works entirely via RSS and web scraping, making it perfect for managing apps released only on Github.
It appears to meet all the requirements for inclusion. It is not included on F-Droid, but that isn't particularly out-of-the-ordinary for app stores.

**Comment by shuvashish76** [comment]
Obtanium getting popular among users, which is really good for faster updates. +1
Some App Stores are outdated in our list, will update with this one. Thanks.
