### ISSUE TITLE
Please Added YTDLnis

### ISSUE THREAD

**Issue by MayaBi7** [offa/android-foss#301]
Category - Downloader & Manager

https://github.com/deniscerri/ytdlnis

**Comment by offa** [comment]
Thanks for your suggestion. The project contains non-free components at the moment – according to https://github.com/deniscerri/ytdlnis/issues/231. Looks like it's on the radar already, so let's wait for a fix.

**Comment by MayaBi7** [comment]
You can Added now...!!👍

**Comment by offa** [comment]
Added :+1:
