### ISSUE TITLE
Remove Ring

### ISSUE THREAD

**Issue by smaragdus** [offa/android-foss#306]
I suppose that **Ring** under section [Messaging](https://github.com/offa/android-foss#-messaging) should be removed because it was renamed to [Jami](https://jami.net/) which is already added to the database and both **Ring** and **Jami** point to one and the same F-Droid [page](https://f-droid.org/packages/cx.ring/). So **Ring** and **Jami** are one and the same app (`cx.ring`). More about the renaming can be found under [FAQ](https://jami.net/help/) (third question- _Why is “Ring” mentioned in the application, website and app stores?_).

**Comment by offa** [comment]
Thanks for the info, update is on the way!
