### ISSUE TITLE
Replace UAD with ADL

### ISSUE THREAD

**Issue by shuvashish76** [offa/android-foss#323]
[Replace](https://github.com/offa/android-foss#-tools-) with [Android Debloat List](https://github.com/MuntashirAkon/android-debloat-list).
Reason : UAD [abandoned](https://github.com/0x192/universal-android-debloater/issues/868).

**Comment by offa** [comment]
Technically it's not a tool, but a list (correct?). Sounds good to me though :+1:.

**Comment by offa** [comment]
Via #324.

**Comment by shuvashish76** [comment]
We've a UAD fork https://github.com/Frigyes06/universal-android-debloater. Add it to  "Tools" list.

**Comment by offa** [comment]
On the way, thanks for the update.

**Comment by shuvashish76** [comment]
@offa As you mentioned ADL is just a database, now we've a fork https://github.com/Universal-Debloater-Alliance/universal-android-debloater.

Add this to the list as well. It got some "Pre-releases"...

**Comment by shuvashish76** [comment]
Updated UAD [new link](https://github.com/Universal-Debloater-Alliance/universal-android-debloater).

**Comment by offa** [comment]
Updated, thanks! :+1:
