### ISSUE TITLE
Call Recorder (suggestion)

### ISSUE THREAD

**Issue by Thestroyer** [offa/android-foss#338]
#### My suggestion is to add [*Call Recorder*](https://f-droid.org/en/packages/com.github.axet.callrecorder/) to the list.   
1. **Licensed as Free and Open Source Software?**
    GPLv3
2. **Source code available?**
    https://gitlab.com/axet/android-call-recorder/
3. **Keeps Privacy – No Advertisement, no Spyware!**
    F-droid labels spywares and apps with *Anti-features*, this app does not have them.
4. **No proprietary elements?**
    Also F-droid would label it.
5. **Stable (at least stable to use) – (if possible)?**
    I am using it for a year or so, so yep - it is stable
6. **Actively developed, maintained or supported – (if possible)?**
    Last release *2023-08-03*
7. **Documentation available (Project website etc.)?**
    Yes, at GitLab https://gitlab.com/axet/android-call-recorder/
8. **Free of charge?**
    It is on F-droid, so basically yes.

btw. Maybe add issue template?

**Comment by offa** [comment]
Looks ok to me, but what category does it fit? Should we add one for call recorders?

> btw. Maybe add issue template?

If all these information are available already – as in your case – feel free to skip the issue an file as PR directly :-)

**Comment by Thestroyer** [comment]
My proposals are (sorted by most favored):
1. [Miscellaneous](https://github.com/offa/android-foss#-miscellaneous) (there is *voice recorder* so it would fit)
2. [System](https://github.com/offa/android-foss#-system) (there is *packet capture* app, so maybe call capture?)
3. [Call blocker & spam filter](https://github.com/offa/android-foss#-call-blocker--spam-filter) (well it fits just a bit)
4. [Dialer](https://github.com/offa/android-foss#-dialer)

So, for me it is obvious - Misc category and for you?

**Comment by offa** [comment]
I guess 1.) fits best :+1:
