### ISSUE TITLE
App proposals

### ISSUE THREAD

**Issue by Thestroyer** [offa/android-foss#340]
I have some FOSS apps proposals, what do you think?:
### Summary:
- [Unitto](https://github.com/sadellie/unitto) [[F-droid](https://f-droid.org/app/com.sadellie.unitto)]
- [WifiAnalyzer](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer) [[F-droid](https://f-droid.org/app/com.vrem.wifianalyzer)]
- [ConnectBot](https://github.com/connectbot/connectbot) [<strike>Only</strike> [Google Play](https://play.google.com/store/apps/details?id=org.connectbot), [F-droid](https://f-droid.org/packages/org.connectbot/) too]
- [AVNC](https://github.com/gujjwal00/avnc) [[F-droid](https://f-droid.org/app/com.gaurav.avnc)]

Plus maybe [nightly releases of Aurora Store](https://auroraoss.com/AuroraStore/Nightly/)? (tbh only them are working for me rn)

#### Unitto

1. Licensed as Free and Open Source Software
    GNU GPL
2. Source code available
    https://github.com/sadellie/unitto
3. Keeps Privacy – No Advertisement, no Spyware!
4. No proprietary elements
5. Stable (at least stable to use) – (if possible)
    I can say stable
6. Actively developed, maintained or supported – (if possible)
   Latest release 2023-11-02
8. Documentation available (Project website etc.)
10. Free of charge

#### WifiAnalyzer

1. Licensed as Free and Open Source Software
    GNU GPL
2. Source code available
    https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer
3. Keeps Privacy – No Advertisement, no Spyware!
4. No proprietary elements
5. Stable (at least stable to use) – (if possible)
    I can say stable
6. Actively developed, maintained or supported – (if possible)
   Latest release 2023-06-27
8. Documentation available (Project website etc.)
10. Free of charge

#### ConnectBot

1. Licensed as Free and Open Source Software
    [Apache License](https://github.com/connectbot/connectbot/blob/main/LICENSE)
2. Source code available
    https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer
3. Keeps Privacy – No Advertisement, no Spyware!
4. No proprietary elements
5. Stable (at least stable to use) – (if possible)
    I can say stable
6. Actively developed, maintained or supported – (if possible)
   Latest release 2023-02-08
8. Documentation available (Project website etc.)
10. Free of charge

#### AVNC

1. Licensed as Free and Open Source Software
    GNU GPL
2. Source code available
    https://github.com/gujjwal00/avnc
3. Keeps Privacy – No Advertisement, no Spyware!
4. No proprietary elements
5. Stable (at least stable to use) – (if possible)
    I can say stable
6. Actively developed, maintained or supported – (if possible)
   Latest release 2023-06-02
8. Documentation available (Project website etc.)
10. Free of charge

**Comment by offa** [comment]
Thanks for your suggestions.

Unitto is in the list already. The others look good, connectbot is [on F-Droid too](https://f-droid.org/app/org.connectbot). Are you interested in submitting those as a PR?

**Comment by offa** [comment]
> Plus maybe nightly releases of Aurora Store? (tbh only them are working for me rn)

Aurora is listed with F-Droid and it's website. Nightly builds are usually relevant for a smaller group only.

**Comment by Thestroyer** [comment]
> Thanks for your suggestions.
> 
> Unitto is in the list already. The others look good, connectbot is [on F-Droid too](https://f-droid.org/app/org.connectbot). Are you interested in submitting those as a PR?

My bad, did not see this connectbot.
But maybe we could move Unitto to [Calculator](https://github.com/offa/android-foss#-calculator) category? Because even after installing it is being displayed as "Calculator" in app list.

**Comment by offa** [comment]
> But maybe we could move Unitto to Calculator category? Because even after installing it is being displayed as "Calculator" in app list.

Sounds good! :+1:

**Comment by Thestroyer** [comment]
> > Plus maybe nightly releases of Aurora Store? (tbh only them are working for me rn)
> 
> Aurora is listed with F-Droid and it's website. Nightly builds are usually relevant for a smaller group only.

I mean it's not easy to find those nightly builds (You have to manually go to Gitlab, go to Aurora OSS link..it's just too much steps), and they can be very usefull (as I said, i'm already using it, because main releases are always buggy bruh). At least some mention or something

**Comment by offa** [comment]
Nightly builds build the current state of the repo and aren't intended for broader use – unless mentioned by the project. While there are good reasons to use them (eg. yours), it's not the default. There's [an issue](https://gitlab.com/AuroraOSS/auroradroid/-/issues/158) requesting more frequent releases, maybe you can ping the aurora devs?

According to it's git log it's not very active anymore, F-droid is dead (404) too!? Do you know whether it's still maintained?

**Comment by Thestroyer** [comment]
What do you mean F-droid is dead? It got [new release in 2023-11-11](https://f-droid.org/en/app/org.fdroid.fdroid) (alpha release)

**Comment by offa** [comment]
No, sorry, I meant the Aurora Droid link of F-Droid: https://f-droid.org/app/com.aurora.adroid

**Comment by Thestroyer** [comment]
Oh yes, Tbh I once tried **Aurora Droid** but it did not work quite well, so I uninstalled it and forgot. F-droid is easy to use, actively maintained and not so ugly, so I guess unfortunately devs abandoned **Aurora Droid**. They should at least add notice it is abandoned though.

Now the question is, should we remove **Aurora Droid** from the list?

**Comment by offa** [comment]
:see_no_evil: There's the reason why it's removed from F-Droid:

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13636

Unfortunately the repo doesn't mention that the project is discontinued, nor is it archived.

**Comment by Thestroyer** [comment]
Uff, sad. Anyway what do you think about adding this nightly link? As I said, It is very hard to find, because it is not even mentioned on gitlab readme (although they have it on screenshots XD). So even people that know risks of using nightly don't know about those releases.

**Comment by shuvashish76** [comment]
> Anyway what do you think about adding this nightly link? As I said, It is very hard to find, because it is not even mentioned on gitlab readme.

Nightly builds are intended for "testers" not general users. Besides that only [F-Droid/IzzyOnDroid links](https://github.com/offa/android-foss/blob/master/CONTRIBUTING.md#f-droid-links) are supported here.

**Comment by Thestroyer** [comment]
> Besides that only [F-Droid/IzzyOnDroid links](https://github.com/offa/android-foss/blob/master/CONTRIBUTING.md#f-droid-links) are supported here.

Not really, there is [Chromium SWE link](https://forum.xda-developers.com/android/apps-games/app-code-aurora-s-chromium-swe-browser-t3603932) in [Browser](https://github.com/offa/android-foss#-browser) category, that is not repo, nor **F-droid** or **IzzyOnDroid** link, so i think another exception would be acceptable. (I'm not forcing you, but because Aurora Store is the only alternative to prioprietary Google Play, it is the only app we can depend on..and this app's oficial releases often disappoints / don't work, so in my opinion people should be allowed to know about nightly releases and decide by themselves if they want to accept risk of using it)

By the way, isn't this **Chromium SWE[[repo](https://github.com/bamless/chromium-swe-updater)]** abandoned? Last commit 2018-05-21.

**Comment by shuvashish76** [comment]
> 
> Not really, there is [Chromium SWE link](https://forum.xda-developers.com/android/apps-games/app-code-aurora-s-chromium-swe-browser-t3603932) in [Browser](https://github.com/offa/android-foss#-browser) category, that is not repo, nor **F-droid** or **IzzyOnDroid** link.

Those hyperlinks are used for the repository of the project which could be anything GitHub, GitLab, Codeberg, SourceForge etc..

> By the way, isn't this Chromium SWE[repo] abandoned? Last commit 2018-05-21.

Yes it looks abandoned, @offa please remove it.

> Aurora Store is the only alternative to prioprietary Google Play, it is the only app we can depend on..and this app's oficial releases often disappoints / don't work.

Yes I noticed it. We appreciate your concern but promoting nightly/betas does more harm as users will be frustrated with frequent breakage/changes. Also how would users download them? While Obtanium like solutions possible it's not good for users privacy/security. We recommend F-Droid (official repo) for general users. If the "stable" release isn't stable enough for users then no point in using it. We can't change the rule for specific apps.

You could ask izzy for [inclusion](https://gitlab.com/IzzyOnDroid/repo/-/issues) for his repo, though I don't think he'll accept it either.

**Comment by Thestroyer** [comment]
Ohkay, I got your pov. Maybe I'll try to convince Aurora Store devs to promote nightly versions a bit, so the project itself gains some interest (cuz for now it looks kind of dead, though it is actively developed).

**Comment by offa** [comment]
Thanks for the hint, i have removed Chromium SWE.
