### ISSUE TITLE
TrackerControl link

### ISSUE THREAD

**Issue by Thestroyer** [offa/android-foss#342]
Why **TrackerControl** link in [Ad Blocker category](https://github.com/offa/android-foss#-ad-blocker), points to [fork](https://github.com/OxfordHCC/tracker-control-android) of [TrackerControl](https://github.com/TrackerControl/tracker-control-android)?

**Comment by offa** [comment]
Maybe the project has moved to an organisation for development and the fork was the main repository before 🤷‍♂️. Thanks for the hint, I'm going to update the entry accordingly.
