### ISSUE TITLE
Add bitwarden F-droid link

### ISSUE THREAD

**Issue by tygoee** [offa/android-foss#350]
Under Password managers > Bitwarden, F-droid isn't specified, but they host an [F-droid repo](https://mobileapp.bitwarden.com/fdroid), and it could be linked there

**Comment by offa** [comment]
They host it on their own 3rd party repository only unfortunately. This list includes only official F-Droid (or izzy Repo) links.

**Comment by tygoee** [comment]
Maybe you could mention that like this

* [**Bitwarden**](https://github.com/bitwarden/mobile) <sup>**[[F-Droid repo](https://mobileapp.bitwarden.com/fdroid)]**</sup>

**Comment by offa** [comment]
3rd party repositories aren't accepted (except Izzy, but that's another story). There are some reasons listed here: https://github.com/offa/android-foss/issues/302#issuecomment-1684255457

**Comment by tygoee** [comment]
Okay that makes sense
