### ISSUE TITLE
Material Notes (Scarlet) discontinued + add Safe Notes maybe

### ISSUE THREAD

**Issue by Thestroyer** [offa/android-foss#351]
Check https://github.com/offa/android-foss#-notes
https://f-droid.org/packages/com.trisven.safenotes/

**Comment by offa** [comment]
Thanks for the hint. I have removed Material / Scarlet Notes. I'm not sure about Safe Notes, it had some activity in the last months on Github and the current release is from this year.

**Comment by Thestroyer** [comment]
I think it's not yet too long to conclude it is abandoned / discontinued, but in context of safety rare updates + no audit can be dangerous...but maybe advertising it here would help it to function..finally user chooses software that meets his needs, so imo adding it is not a bad idea.

Also another app what do you think?: https://f-droid.org/en/packages/com.standardnotes/

**Comment by offa** [comment]
Standard notes added :+1:
