### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by alxnbl** [offa/android-foss#357]
Hey @offa , I would like to contribute to this project to propose a french version of the list of alternative.

Would you be interested by a contribution to this repo, or do you prefer that I initiate a fork on my side ?
If you are interested to integrate the translation in your repo, do you have any idea of the best way to manage internationalization ? 

Regards
Alex

**Comment by offa** [comment]
Translations would be great, but I don't really know a good way of doing it. While the content of tutorials/ doesn't change very often, the main list does. Suggestions welcome.

**Comment by alxnbl** [comment]
I don't see any perfect solution either.

A complex solution would be to make an evolution to your repo to evolve from a simple Markdown file into a Multilingual Jekyll website deployed on Git Pages. Readme.md will evolve to replace static english text by dynamic translation based on Liquid syntax, coupled to a translation file. People will go to GitHub to contribute to project, while going to Git Pages to consult the list of alternatives. If you don't know Jekyll, you can have a look to this project I am working on : https://github.com/alxnbl/digital-alternatives deployed on git Pages https: https://alxnbl.github.io/digital-alternatives/ .

A much more simple and basic solution would be that I create a fork "android-foss-fr" of you repo. I translate the Readme.md file into french and periodically I create a merge request to refresh my repo from yours. 

What do you think ?

**Comment by offa** [comment]
Github pages is way too overkill for this project I think.

There are some projects which support markdown translations based on some kind of template ([example](https://github.com/ryul1206/multilingual-markdown)) – but haven't used one myself yet. There might be others / better.

The main idea is to translate the actual list (readme.md), not the other files? It doesn't contain much text, but rather headlines; so the goal is translation of the headlines?

**Comment by alxnbl** [comment]
I checked out the projet [multilingual-markdown](https://github.com/ryul1206/multilingual-markdown), it looks interessting. Seams pretty simple to execute, and allow to maintain a single md file.

My idea was indeed to translate the headlines of the the software list (readme.md). My usecase is that I am developing a website that aim at helping french people with no tech knowledge to adopt opensource / ethic softwares. And ideally I would like to present a list like the one you are maintaining but with categories in french, and ideally rendered as a simple webpage.

But most GitHub repositories are targeting tech people who are comfortable with english. So I don't know if it makes sens for your repo to add this complexity layer of translation ?

Whatever the answer, a good solution for my need would be to embded a kind of copy of your list in my website, translating headlines and linking back to your repo for credits and peoples wanting last update version. Would you be happy with this solution ?

**Comment by offa** [comment]
> My usecase is that I am developing a website that aim at helping french people with no tech knowledge to adopt opensource / ethic softwares.

Wow, nice! :+1: 

> So I don't know if it makes sens for your repo to add this complexity layer of translation ?

Yes, that's a point. Especially as markdown might not be the perfect solution for your use case.

> Whatever the answer, a good solution for my need would be to embded a kind of copy of your list in my website, translating headlines and linking back to your repo for credits and peoples wanting last update version. 

It could work to either do an automated kind of search-and-replace for the headlines, or to parse the markdown and emit a translated version.

**Comment by alxnbl** [comment]
OK I will go for the the option of translating the file on my side, manually as a beginning, and I will consider later how to automate updates.
Thanks for your help!
