### ISSUE TITLE
Keep eye on Quik (possibly new fork of QKSMS), new app DataBackup

### ISSUE THREAD

**Issue by Thestroyer** [offa/android-foss#358]
https://github.com/octoshrimpy/quik
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14515

DataBackup:
https://github.com/XayahSuSuSu/Android-DataBackup
https://f-droid.org/app/com.xayah.databackup.foss

**Comment by offa** [comment]
Thanks! I have added quik and DataBackup.

I'll leave open here as the quik F-Droid PR has not yet been merged and it's a good reminder.

**Comment by offa** [comment]
Quik is available on F-Droid now, link added :+1:

**Comment by offa** [comment]
> @offa You fast hehe, but shouldn't that be in submenu of QKSMS?

There aren't that much entries in the section yet; do you have preference? :-)

**Comment by Thestroyer** [comment]
Imo as it is strictly related with QKSMS (fork of it), it should have some relation (so submenu) with it. 

> do you have preference? :-)
wdym?
