### ISSUE TITLE
Add Tubular

### ISSUE THREAD

**Issue by basings** [offa/android-foss#361]
Tubular is the successor to newpipe https://github.com/polymorphicshade/Tubular

**Comment by shuvashish76** [comment]
It replaces "NewPipe x SponsorBlock x Return YouTube Dislike" from the same dev so remove that app.
See their [readme](https://github.com/polymorphicshade/NewPipe#development-has-stopped).

**Comment by offa** [comment]
Thanks for the update. The name definitely improved :smile:.
