### ISSUE TITLE
pocket broomball

### ISSUE THREAD

**Issue by RustoMCSpit** [offa/android-foss#368]
https://github.com/dulvui/pocket-broomball/releases

**Comment by offa** [comment]
Thanks, do you have a suggestion under which category it could fit?

**Comment by RustoMCSpit** [comment]
game

**Comment by offa** [comment]
But what subcategory?

**Comment by RustoMCSpit** [comment]
> But what subcategory?

misc

**Comment by offa** [comment]
Thanks, added :+1:
