### ISSUE TITLE
Remove BlackHole

### ISSUE THREAD

**Issue by shuvashish76** [offa/android-foss#371]
https://gitlab.com/fdroid/fdroiddata/-/issues/3219

BlackHole project went into blackhole removed from Telegram, GitHub, Izzy, F-Droid...
I guess they removed for piracy reasons (used to fetch music from https://www.jiosaavn.com/ an [Indian music streaming service](https://en.wikipedia.org/wiki/JioSaavn))

No active FOSS forks yet, many projects appearing on Google search results & Telegram but all are fake/mods/proprietary.
The app from F-Droid archive repo works for now.

**Comment by offa** [comment]
Removed, thanks for the update @shuvashish76!
