### ISSUE TITLE
Replace YetAnotherCallBlocker with Tranquille

### ISSUE THREAD

**Issue by shuvashish76** [offa/android-foss#372]
See https://github.com/Vinetos/Tranquille/issues/1
https://gitlab.com/fdroid/rfp/-/issues/2694

Keep it open for until they make their 1st release / F-Droid inclusion.

**Comment by offa** [comment]
Thanks for the update!

First part is done :-)

**Comment by offa** [comment]
I have removed the app as the project is no longer active. F-Droid packaging has already been closed due to inactivity.

**Comment by shuvashish76** [comment]
Last commit in [sql_delight branch](https://github.com/Vinetos/Tranquille/tree/feature/sql_delight) 3weeks ago. Development is slow/inactive but not abandoned. I agree no point in adding it to our list _for now_.
