### ISSUE TITLE
Remove and add translation apps

### ISSUE THREAD

**Issue by Ryttch** [offa/android-foss#376]
Remove:
[Arna Translate](https://github.com/MahanRahmati/translate/issues/135) (Abandoned)
[LibreTranslator](https://codeberg.org/BeoCode/LibreTranslator) (Not maintained)

Add:
[Lentil Translate](https://github.com/yaxarat/lingvaandroid) [[F-Droid](https://f-droid.org/packages/dev.atajan.lingva_android/)]

**Comment by offa** [comment]
List updated, thanks you! :+1:
