### ISSUE TITLE
Webpage auto redirecting to chrome 

### ISSUE THREAD

**Issue by nascentphilosopher** [offa/android-foss#379]

**Comment by offa** [comment]
What's the actual topic here?

**Comment by nascentphilosopher** [comment]
This version frequently redirecting to chrome unlike previous version!!

**Comment by offa** [comment]
Why should this project redirect to Chrome? It's mainly markdown.

**Comment by nascentphilosopher** [comment]
Bug Report
Url/websites redirecting to chrome browser
