### ISSUE TITLE
Add a link to Cromite's custom F-Droid repo

### ISSUE THREAD

**Issue by codenyte** [offa/android-foss#381]
https://www.cromite.org/fdroid/repo/?fingerprint=49F37E74DEE483DCA2B991334FB5A0200787430D0B5F9A783DD5F13695E9517B

**Comment by offa** [comment]
Only official F-Droid, or with some limitations Izzys repo are linked here (see [contributing](https://github.com/offa/android-foss/blob/master/CONTRIBUTING.md#f-droid-links) for more details).
