### ISSUE TITLE
Duplicate Under 'SMS' Section

### ISSUE THREAD

**Issue by via80HD** [offa/android-foss#389]
As you can see from the screenshot below, there are 3 options under the SMS section heading. 
![Screenshot](https://ia800407.us.archive.org/4/items/screenshot-20240614-153905-1/Screenshot_20240614-153905_1.png)

The 2nd & 3rd choices will ultimately take you to the same page (though the urls are different) they will ultimately have you install the same exact app - which is QKSMS.

**Comment by offa** [comment]
I've just tried both links – Github and F-Droid – and they point to the correct projects, QKSMS and Quick.

**Comment by offa** [comment]
Can anyone reproduce this?

**Comment by vdbhb59** [comment]
QKSMS & QUIK are separate.
QUIK is the fork of QKSMS. I use both QKSMS & QUIK. They are separate.
