### ISSUE TITLE
Add King Crimson (YouTube ad skip)

### ISSUE THREAD

**Issue by sanjacob** [offa/android-foss#393]
King Crimson is a small service that auto-skips YouTube ads (on the browser).
It relies on the media controls to do so rather than a VPN or a browser extension, which is desirable to some users.

While there a few YouTube clients on the list, as well as general ad blockers, this might be a good addition for people who already have DNS ad blocking but need a solution only for YouTube. I developed this for my own use (Graphene OS), but think there are some people who could find this useful as well.

You can find the app source here: https://github.com/sanjacob/KingCrimson
Currently there is no F-Droid package, but in the future that may change.

Let me know what you think

**Comment by offa** [comment]
Thanks, your project sounds interesting! :+1: 

Since it's quite new, I'd rather give it a little more time, since there's not much usage experience. Otherwise it looks good and promising.

>  Currently there is no F-Droid package, but in the future that may change.

You should deferentially consider this. As far as I can tell, it shouldn't be too complicated.

**Comment by shuvashish76** [comment]
@sanjacob [Requested](https://gitlab.com/IzzyOnDroid/repo/-/issues/565) at IzzyOnDroid.
IzzyOnDroid, needs properly signed release build. Also please add [Fastlane](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/) metadata for example see : [AppManager](https://github.com/MuntashirAkon/AppManager/tree/master/fastlane/metadata/android/en-US).

**Comment by sanjacob** [comment]
@shuvashish76 lately I have been more variation in the way YouTube presents ads. While the app still stops 40%-60% of ads there are some which cannot be easily identified. So I'm holding back for now.
