### ISSUE TITLE
foss

### ISSUE THREAD

**Issue by pihie** [offa/android-foss#394]
will there ever be foss guides for other os platforms?

**Comment by offa** [comment]
Could you please provide more details or clarify the question?

**Comment by offa** [comment]
@pihie is your question answered?

**Comment by pihie** [comment]
> @pihie is your question answered?

No
I meant if you are going to make them

**Comment by offa** [comment]
I appreciate the suggestion, but I'm not considering that at the moment.

**Comment by pihie** [comment]
My question has been answered
