### ISSUE TITLE
New apps 

### ISSUE THREAD

**Issue by gigachaand** [offa/android-foss#403]
Weather - 
https://github.com/darkmoonight/Rain

Password & Authentication - 
https://github.com/ente-io/ente/releases/tag/auth-v3.0.18-beta.2

**Comment by shuvashish76** [comment]
> Password & Authentication - https://github.com/ente-io/ente/releases/tag/auth-v3.0.18-beta.2

Already in [Image Viewer & Gallery](https://github.com/offa/android-foss#-image-viewer--gallery)
