### ISSUE TITLE
Replace Unitto with NumberHub

### ISSUE THREAD

**Issue by shuvashish76** [offa/android-foss#405]
Unitto was originally requested by the developer himself #258 here. But some reason they decided to archive the repository. Let's remove & replace it with it's fork [NumberHub](https://github.com/Myzel394/NumberHub).

Upstream issue: https://github.com/Myzel394/NumberHub/issues/7

**Comment by sitiom** [comment]
- https://github.com/offa/android-foss/pull/400

**Comment by shuvashish76** [comment]
Sorry for the duplicate
