### ISSUE TITLE
Remove Telegram Monet

### ISSUE THREAD

**Issue by shuvashish76** [offa/android-foss#415]
Asked about their license here: https://github.com/mi-g-alex/Telegram-Monet/issues/74
Until resolved let's remove it from the list.

**Comment by shuvashish76** [comment]
Looks like that added Eclipse Public License 2.0 license which is approved by both FSF and OSI. (see [SPDX list](https://spdx.org/licenses/))

**Comment by offa** [comment]
Thanks for the clarification! :-)
