### ISSUE TITLE
Add InnerTune forks

### ISSUE THREAD

**Issue by shuvashish76** [offa/android-foss#438]
Add forks under InnerTune
- https://github.com/Malopieds/InnerTune (Name and icon : https://github.com/Malopieds/InnerTune/issues/29, Already available on IzzyOnDroid : https://apt.izzysoft.de/fdroid/index/apk/com.malopieds.innertune )
- https://github.com/DD3Boh/OuterTune (relevant issue : https://github.com/DD3Boh/OuterTune/issues/23)

**Comment by offa** [comment]
Added, thanks!

**Comment by offa** [comment]
:see_no_evil: Indeed, they are …

Fixed, thanks!

**Comment by shuvashish76** [comment]
Add one more fork https://github.com/Arturo254/OpenTune

**Comment by offa** [comment]
OpenTune includes [Firebase](https://github.com/Arturo254/OpenTune/blob/master/app/src/full/java/com/zionhuang/music/utils/Utils.kt). However, no detailed analysis on my part yet.
