### ISSUE TITLE
Add AutoPie

### ISSUE THREAD

**Issue by cryptrr** [offa/android-foss#444]
AutoPie is basically a Swiss Army Knife for Android. Lets you create and automate with Linux commands on Android in a few clicks. 

Github link: [https://github.com/cryptrr/AutoPie](https://github.com/cryptrr/AutoPie)

**Comment by offa** [comment]
Looks good to me :+1: 

Thanks for your development and [considering F-Droid](https://gitlab.com/fdroid/rfp/-/issues/2878) too!

**Comment by cryptrr** [comment]
Yeah. I can do that :)

**Comment by cryptrr** [comment]
@offa Is the line endings used CRLF. Is the os this repo had been made Windows.

I'm on a mac so diff would change line endings on all lines to the mac/linux LF instead of Windows CRLF.

Does not change anything. But the diffs will unnecessarily show changes.

Can you confirm it. If yes, I would use the windows Line endings instead..
