### ISSUE TITLE
File Encryption apps

### ISSUE THREAD

**Issue by shuvashish76** [offa/android-foss#446]
I think we need a separate category for file encryption tools
- Cryptomator : https://f-droid.org/en/packages/org.cryptomator.lite/ _(license required)_
  - reference: https://docs.cryptomator.org/en/latest/security/architecture/
- DroidFS : https://f-droid.org/packages/sushi.hardcore.droidfs/ supports the following encrypted containers:
  - [gocryptfs](https://github.com/rfjakob/gocryptfs): encrypts file contents and file names but doesn't hide directory structure or file sizes. (info: [comparison](https://nuetzlich.net/gocryptfs/comparison/))
  - [CryFS](https://github.com/cryfs/cryfs): slower, but encrypts everything and obfuscates file sizes. (info: [comparision](https://www.cryfs.org/comparison))
- EDS Lite : https://f-droid.org/packages/com.sovworks.edslite/ {Project looks inactive no updates on F-Droid since 2021 but it's the only option for veracypt}. Supports [VeraCrypt](https://veracrypt.fr/) (foss), TrueCrypt(Freeware), [LUKS](https://gitlab.com/cryptsetup/cryptsetup) (foss), EncFs (not maintained, recommends gocryptfs instead) container formats. See difference between full vs lite [here](https://sovworks.com/eds/).
- Koofr Vault : https://f-droid.org/packages/net.koofr.vault/ 

---

For example there are [KPDX](https://f-droid.org/en/packages/com.kunzisoft.keepass.libre/) (for passwords/TOTP), [Valv ](https://f-droid.org/en/packages/se.arctosoft.vault/)(for gallery), [Dairy Vault](https://github.com/SankethBK/diaryvault) (for dairy) , [Aegis](https://f-droid.org/en/packages/com.beemdevelopment.aegis/) (for TOTP), [AppManager](https://f-droid.org/packages/io.github.muntashirakon.AppManager) ([encrypted](https://muntashirakon.github.io/AppManager/en/#subsubsec:settings-encryption) app backups), [Neo Backup](https://f-droid.org/packages/com.machiav3lli.backup/) (again for apps and data) etc. They're all some kind of file encryption tools but the user should use relevant tools for specific intended purposes only.

I think "File Encryption apps" requires it's special category they're intended to be use for all type of files.

**Comment by offa** [comment]
Indeed, this sound like a good idea! :+1:

**Comment by offa** [comment]
@shuvashish76 I have created a PR for the category.

- Category 'Encryption' added (do we really need to limit it to files?)
- Suggested projects added, except EDS Lite as I'm not sure about it (using a security related project that's inactive for years?) – but I see your point, so we might add it if you think we should.
- Valv moved to the new category

Please let me know what you think.

**Comment by shuvashish76** [comment]
>     * Category 'Encryption' added (do we really need to limit it to files?)

IMO yes i.e. intended to use any type of files in general. 

>     * Suggested projects added, except EDS Lite as I'm not sure about it (using a security related project that's inactive for years?) – but I see your point, so we might add it if you think we should.

Arch linux wiki recommends these https://wiki.archlinux.org/title/Data-at-rest_encryption#Cloud-storage_optimized DroidFS already supports 2 of them and we've official client for Cryptomator. I think we can skip this inactive app.

**Comment by shuvashish76** [comment]
New tool for this "File Encryption" category: https://f-droid.org/en/packages/io.github.picocrypt_ng.picocrypt_ng/ (info: [comparison](https://github.com/Picocrypt-NG/Picocrypt-NG#comparison))

**Comment by offa** [comment]
Added, thanks!
