### ISSUE TITLE
add notallyx

### ISSUE THREAD

**Issue by CodeNomadHQ** [offa/android-foss#458]
NotallyX is an upgraded version of Notally, offering an eXtended minimalistic note-taking experience.

Here is the link to GitHub [repository](https://github.com/PhilKes/NotallyX), and the link to [F-Droid](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/16073) listing, which is currently under review.

**Comment by offa** [comment]
Added, thanks. :+1:
