### ISSUE TITLE
Time to remove DivestOS apps

### ISSUE THREAD

**Issue by shuvashish76** [offa/android-foss#476]
https://infosec.exchange/@divested/113703337476638702 :(
All the apps are now archived : https://github.com/Divested-Mobile
Eventually apps will be moved to F-Droid's archive repo for TWIF news updates subscribe their [RSS feed](https://f-droid.org/en/news/).

**Comment by offa** [comment]
Sad news … :-(

**Comment by shuvashish76** [comment]
Add https://gitlab.com/ironfox-oss/IronFox fork of Mull.

**Comment by offa** [comment]
Added, thanks @shuvashish76 :+1:
