### ISSUE TITLE
Add fbreader

### ISSUE THREAD

**Issue by azzamsa** [offa/android-foss#49]
https://github.com/geometer/FBReaderJ

**Comment by offa** [comment]
Is this project still active and FOSS? According to their [website](https://fbreader.org/android) recent releases aren't open source any more:

> Until release 2.7, FBReader source code was dual licensed: GPL and commercial. Unfortunately, GPL violations were too regular. _**Since 2.7 the source code is only available for a fee.**_

There's another [book reader](https://f-droid.org/de/packages/com.github.axet.bookreader/) based on fbread though, maybe that's a better choice?

**Comment by azzamsa** [comment]
@offa my main problem in android only one: pdf reader that able to anotate, I can't find any kind like okular in gnu/linux world. Do you have any suggestion ?

**Comment by offa** [comment]
> Do you have any suggestion ?

Unfortunately not, I'm using them for reading only. Probably you can have a look at [Book Reader](https://f-droid.org/de/packages/com.github.axet.bookreader/) linked above. It's based on FBReader and some other projects (but I worry that it doesn't include annotations neither).

**Comment by offa** [comment]
I have added Book Reader, it's sounds handy! :+1:

**Comment by azzamsa** [comment]
Fixes https://github.com/offa/android-foss/commit/cec8c2fe38a92993c1ce98767bb84d391a542864
