### ISSUE TITLE
List format

### ISSUE THREAD

**Issue by azzamsa** [offa/android-foss#50]
Hi

What if we reformat the list, I think it's better if a user can get small detail of app at glimpse.

```
- app name with link - app description - app license
```

**Comment by offa** [comment]
I thought about this earlier, but in most cases it clutters the list without adding much value. In many cases the description within a category boils down to same or similar text. A user can get comprehensive information by the particular website / F-droid page. A proper categorization should provide a list of candidates and an overview of what's available (… at least, I hope so :crossed_fingers: ). Keeping the descriptions reasonably up to date is another story …

Like the description, the license may change in a projects life and it's typically only a click away (either website or F-droid). My list doesn't provide much information about licensing, that's true. But as only FOSS licensed projects are listed here, one can get at least the information "_it's free and open source_".

Maintain the KISS principle :-)

**Comment by azzamsa** [comment]
Indeed, since it's your baby :), I agree with you on this.
