### ISSUE TITLE
Medito - Minfulness and Meditation

### ISSUE THREAD

**Issue by michaelspeedcode** [offa/android-foss#83]
https://meditofoundation.org/
https://gitlab.com/medito/medito-app

**Comment by offa** [comment]
Thanks for your suggestion. Unfortunately it seems to contain proprietary services and even tracking.

If you have some time, it's always a good idea to contact the devs regarding a pure FOSS version or even F-Droid packaging.

**Comment by offa** [comment]
I'll close here for now. Please let me know if there's a FOSS version.
