### ISSUE TITLE
app proposal: bitwarden [security], lanxchange and kouchat [new category?]

### ISSUE THREAD

**Issue by sidmint** [offa/android-foss#95]
app proposals:  
bitwarden [security], 
lanxchange, kouchat [may need a new category]

**Comment by offa** [comment]
Thanks for your suggestions. Just take make sure I've found the correct projects:

- https://github.com/bitwarden/mobile — According to https://github.com/bitwarden/mobile/issues/6#issuecomment-584002060 the F-droid version doesn't contain any proprietary parts and the tracking has been removed too :+1: 
- https://github.com/tfg13/LanXchange — looks like no longer maintained :-(
- https://github.com/blurpy/kouchat-android / https://f-droid.org/en/packages/net.usikkert.kouchat.android/ — still maintained?

**Comment by sidmint** [comment]
All the projects are correct, and yes we're seeing lack of maintenance for
lanx* and kou*

**Comment by offa** [comment]
I've added Bitwarden and KouChat. Unfortunately, LanXchange is outdated and unmaintained.
