### ISSUE TITLE
Update active apps and add new ones

### ISSUE THREAD

**Issue by verylongusername69** [offa/android-foss#97]
HayaiLauncher is no longer active and it's not found in F-Droid. It's been forked and actively developed by new app called Keikai Launcher.
Also one of the newest and faster growing launchers is posidon launcher.
For weather app you can add Forecastie, which has more modern and simplistic design.
As for keyboards deffinitely add Simple Keyboard ;)
As for browsers you can add DuckDuckGo Privacy Browser.

**Comment by offa** [comment]
Thanks, for your suggestions. I'll update the list accordingly. :+1:

**Comment by offa** [comment]
[KeikaiLauncher](https://github.com/KeikaiLauncher/KeikaiLauncher) doesn't look very active either …

Everything else is integrated.
