### ISSUE TITLE
my reviews and suggestions

### ISSUE THREAD

**Issue by sreeharimkl** [offa/android-foss#98]
1. i found some apps are not updated yet from a long..check these
- Lightning browser
- Calculater
- Clean Calculater
- offline-calendar(stopped project)
- Clock+
- Talalarmo
- emerald-dialer
- document-viewer
- Dir file manager
- Privacy Friendly Torchlight

2. does appstore in the list means which only provide opensource apps? because aurorastore(playstore client) missing there!

checked this much 😅😅 .. outdated app may cause issues in newer android versions that's why i suggesting to remove these from the list.. anyways i am happy to contribute in this repo and to help you. will check others and i wish to add some other apps into the list and give a pull request

**Comment by offa** [comment]
Thanks I'll have a look at the list. In some cases I guess they are simply feature complete (like a clock or a torchlight), in others ( offline-calendar) it's obvious.

> does appstore in the list means which only provide opensource apps? because aurorastore(playstore client) missing there!

Typically, yes. However, it's still a point to discuss maybe. Aurora Store itself is FOSS (and even on F-Droid), but it's like the entry to a huge proprietary lump on the other side.

**Comment by offa** [comment]
I have removed the obviously outdated / inactive apps. The other still show some sort activity (commits, issues, etc.) and are simple enough to not require too much maintenance.

**Comment by sreeharimkl** [comment]
@offa yah they are feature complete, but if they didn't update it Which may show warning like "this app was build for an older version of Android" and may be stability issues.. But I didn't checked those apps personally.. Will report later if any of app have compatibility issue in newer Android

**Comment by offa** [comment]
Wooops, accidentally removed the wrong "emerald" one :man_facepalming: 

If there are some stability or compatibility issues, please report them upstream :-). Maybe they can fix it. But yes, if there are some is issues and it's more or less sure they wont get addressed, it's better to remove them.

I'm not an android developer myself so I can't say much about app compatibility between android version. Typically a lower bound version is included at F-Droid (and maybe checked by the client!?).

**Comment by sreeharimkl** [comment]
> If there are some stability or compatibility issues, please report them upstream :-). Maybe they can fix it. But yes, if there are some is issues and it's more or less sure they wont get addressed, it's better to remove them.

Yah sure.. Btw Clean Calculator is no longer under active development..

**Comment by offa** [comment]
Right … it's even on the readme.

**Comment by sreeharimkl** [comment]
> I'm not an android developer myself so I can't say much about app compatibility between android version. Typically a lower bound version is included at F-Droid (and maybe checked by the client!?).

I don't know about it Well😅.. I guess I didn't checked things well before create issue.. Sry

**Comment by offa** [comment]
No problem, and thanks again for your efforts!

**Comment by sreeharimkl** [comment]
> Typically, yes. However, it's still a point to discuss maybe. Aurora Store itself is FOSS (and even on F-Droid), but it's like the entry to a huge proprietary lump on the other side.

I agree.. But still most FOSS are published on play store too.. And I have seen some open source developers are publishing and maintaining apps in playstore better.. And may be some apps only available in playstore as it's the large store to get more active users.. Emm.. That's why I am suggesting aurora store in the list..

**Comment by offa** [comment]
Aurora store itself is FOSS, so I'm going to add it.
